#!/bin/sh /etc/rc.common
USE_PROCD=1
START=97
STOP=11

PROG=/usr/bin/xray
CONF=/etc/xray/vpn-policy.json

start_service() {
  [ -f "$CONF" ] || return 1
  procd_open_instance vpn-policy
  procd_set_param command "$PROG" run -config "$CONF"
  procd_set_param env XRAY_LOCATION_ASSET=/usr/share/xray
  procd_set_param file "$CONF"
  procd_set_param limits nofile="1000000 1000000"
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_set_param respawn
  procd_close_instance
}

reload_service() { stop; start; }
