#!/bin/sh /etc/rc.common
USE_PROCD=1
START=99
STOP=3

start_service() {
  [ -f /etc/vpn-guardian/bootstrap-complete ] && return 0
  [ -s /etc/vpn-guardian/stack.json ] || return 0
  [ -s /etc/vpn-guardian/routing.json ] || return 0

  procd_open_instance vpn-guardian-bootstrap
  procd_set_param command /usr/bin/vpn-guardian bootstrap --non-interactive
  procd_set_param stdout 1
  procd_set_param stderr 1
  procd_close_instance
}
